### ISSUE TITLE
Encountered a issue while using the waydroid-script pkgs.

### ISSUE THREAD

**Issue by synebula** [AtaraxiaSjel/nur#3]
I'm sorry for the interruption. Encountered a issue while using the waydroid-script pkgs. I encountered an error after calling waydroid-script following installation. Here is the error message:
``` bash
INFO: Resizing /var/lib/waydroid/images/system.img to 4170M
INFO: Mounting /var/lib/waydroid/images/system.img to /tmp/waydroid
WARN: /tmp/waydroid is not a mount point
INFO: Mounting /var/lib/waydroid/images/vendor.img to /tmp/waydroid/vendor
WARN: /tmp/waydroid/vendor is not a mount point
INFO: Downloading libhoudini.zip now to /home/alex/.cache/waydroid-script/downloads/libhoudini.zip .....
INFO: Extracting /home/alex/.cache/waydroid-script/downloads/libhoudini.zip to /tmp/houdiniunpack
INFO: Copying libhoudini library files ...
Traceback (most recent call last):
  File "/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/bin/.waydroid-script-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/lib/python3.10/site-packages/main/main.py", line 339, in main
    interact()
  File "/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/lib/python3.10/site-packages/main/main.py", line 246, in interact
    install_app(args)
  File "/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/lib/python3.10/site-packages/main/main.py", line 107, in install_app
    item.install()
  File "/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/lib/python3.10/site-packages/stuff/general.py", line 180, in install
    self.add_props()
  File "/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/lib/python3.10/site-packages/stuff/general.py", line 76, in add_props
    shutil.copy(os.path.join(os.path.join(os.path.dirname(__file__), "..", "bin",
  File "/nix/store/bc45k1n0pkrdkr3xa6w84w1xhkl1kkyp-python3-3.10.12/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/bc45k1n0pkrdkr3xa6w84w1xhkl1kkyp-python3-3.10.12/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/ikx8ryaa8gy155qqnck3ri2hchhd4bpw-waydroid-script-unstable-2023-08-25/lib/python3.10/site-packages/stuff/../bin/x86_64/resetprop'
```

I'm referring to this post at the same time, but the issue wasn't resolved.

> https://www.reddit.com/r/NixOS/comments/15k2jxc/need_help_with_activating_libhoudini_for_waydroid/

**Comment by AtaraxiaSjel** [comment]
@synebula Hi! It's great to see someone using my repo :)
I'm using the nix-update script to automatically update packages in this Nur repository and it appears that something might have broken with the latest update. I will look into it and try to resolve the issue in the next few days.

**Comment by synebula** [comment]
Thanks a lot, it's very useful !
Waiting for your good news.

**Comment by synebula** [comment]
It's worked well! You're my hero~
